// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/27/2025, 3:41:34 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/plugins/**/*.{js,ts,mjs}","/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/composables/**/*.{js,ts,mjs}","/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/utils/**/*.{js,ts,mjs}","/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/dpakkia/Documents/Sviluppo/hyperfocus-website/hyperfocus-website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;